version: 0.2
phases:
    install:
        commands:
            # install Node 16
            - curl -fsSL https://deb.nodesource.com/setup_18.x | -E bash - &&\
            - apt install -y nodejs

    pre_build:
        commands:
            # install dependencies
            - npm i

    build:
        commands:
            - npm start

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: .
